/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Định nghĩa thông điệp dữ liệu cảm biến */
typedef struct _SensorMessage {
    uint32_t device_id; /* ID của thiết bị (ví dụ: 1, 2, 3) */
    float temperature; /* Giá trị nhiệt độ */
    float humidity; /* Giá trị độ ẩm */
    uint32_t lux; /* Cường độ ánh sáng */
    bool led_status; /* Trạng thái đèn LED (ON/OFF) */
} SensorMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorMessage_init_default               {0, 0, 0, 0, 0}
#define SensorMessage_init_zero                  {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorMessage_device_id_tag              1
#define SensorMessage_temperature_tag            2
#define SensorMessage_humidity_tag               3
#define SensorMessage_lux_tag                    4
#define SensorMessage_led_status_tag             5

/* Struct field encoding specification for nanopb */
#define SensorMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, UINT32,   lux,               4) \
X(a, STATIC,   SINGULAR, BOOL,     led_status,        5)
#define SensorMessage_CALLBACK NULL
#define SensorMessage_DEFAULT NULL

extern const pb_msgdesc_t SensorMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorMessage_fields &SensorMessage_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_PB_H_MAX_SIZE                     SensorMessage_size
#define SensorMessage_size                       24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
